
module.exports.month_id_list = [
  ["November-17", 15601729],
  ["October-17", 15384262],
  ["September-17", 15148885],
  ["August-17", 14901313],
  ["July-17", 14688684],
  ["June-17", 14460777],
  ["May-17", 14238005],
  ["April-17", 14023198]
];

module.exports.region_filter_list = [
  ["All", []],
  ["Remote", ["remote/i"], ["no remote/i"]],
  ["Arkansas", ["Arkansas", "Little Rock"]],
  ["Arizona", ["Arizona", "Phoenix", "PHX", "Scottdale"]],
  ["California", ["California", "San Francisco", "San Diego", 
                 "Los Angeles", "Bay Area", "SF", "LA", "San Mateo",
                 "Mountain View", "Irvine", "Orange County",
                 "Palo Alto", "Menlo Park", "San Jose", "Sunnyvale",
                 "Cupertino", "Santa Clara", "CA", "Redwood"]],
  ["Colorado", ["Colorado", "CO", "Boulder"]],
  ["Florida", ["Florida", "FL", "Orlando", "Miami", "Fort Lauderdale"]],
  ["Idaho", ["Idaho", "ID", "Boise"]],
  ["Illinois", ["Illinois", "Chicago"]],
  ["Kansas", ["Kansas", "KS"]],
  ["Maryland", ["Maryland", "MD", "Baltimore"]],
  ["Massachusetts", ["Massachusetts", "MA", "Boston", "BOS"]],
  ["Michigan", ["Michigan", "MI", "Detroit"]],
  ["Minnesota", ["Minnesota", "Minneapolis", "MSP"]],
  ["New Hampshire", ["New Hampshire", "NH", "Nashua"]],
  ["New York", ["New York", "NY", "NYC", "Buffalo", "Brooklyn"]],
  ["North Carolina", ["North Carolina", "NC", "Charlotte", "Raleigh"]],
  ["Ohio", ["Ohio", "Cleveland", "Columbus"]],
  ["Oregon", ["OR", "Portland", "Oregon"]],
  ["Pennsylvania", ["Pennsylvania", "PA", "Pittsburgh", "Philadelphia"]],
  ["Texas", ["Texas", "TX", "Austin", "Houston", "Dallas"]],
  ["Utah", ["Utah", "Salt Lake City", "SLC"]],
  ["Virginia", ["Virginia", "Richmond", "Reston", "VA"]],
  ["Washington", ["WA", "Seattle", "Bellavue", "Redmond"]],
  ["Washington DC", ["DC"]],

  ["Australia", ["Melbourne", "Sydney", "Brisbane", "Perth", "Australia"]],
  ["Austria", ["Vienna", "Austria"]],
  ["Canada", ["Vancouver", "Canada", "Montreal", "Toronto", "Quebec"]],
  ["Colombia", ["Colombia"]],
  ["Denmark", ["Denmark", "Copenhagen"]],
  ["Estonia", ["Estonia", "Tallinn"]],
  ["France", ["France", "Paris"]],
  ["Germany", ["Germany", "Berlin", "Munich", "Hamburg", "Cologne"]],
  ["Ireland", ["Ireland", "Dublin"]],
  ["Israel", ["Israel", "Tel Aviv"]],
  ["Italy", ["Italy", "Venice", "Florence", "Milan"]],
  ["Netherlands", ["Amsterdam", "Netherlands"]], 
  ["Singapore", ["Singapore"]],
  ["Spain", ["Spain", "Barcelona"]],
  ["Switzerland", ["Switzerland", "Lausanne"]],
  ["Sweden", ["Sweden", "Stockholm"]],
  ["UK", ["London", "UK", "Birmingham", "Manchester", "Glasgow",
         "Newcastle", "Edinburgh"]],
];


